spring:
  application:
    name: Spring Batch Example


  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: never


  datasource:
    url: jdbc:mariadb://localhost:3306/spring_batch_example
    username: root
    password: root123
    driver-class-name: org.mariadb.jdbc.Driver


  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create

